// Generated by the SDL Java backend.
import java.io.ByteArrayOutputStream;
import java.lang.reflect.Array;
import java.nio.ByteBuffer;
import java.nio.charset.CharacterCodingException;
import java.nio.charset.CharsetDecoder;
import java.nio.charset.CodingErrorAction;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

/** Dependency-free SDL wire codec using Java 7 APIs. */
public final class SdlCodec {
   private static final boolean LITTLE = "little".equalsIgnoreCase(System.getenv("SDL_WIRE_ENDIAN"));
   private static final int MAX_DESCRIPTOR = 1024 * 1024;
   private SdlCodec() {}
   public interface Message {}
   public interface EnumValue { int wireValue(); }
   public static final class Field {
      public final long id; public final String name, modifier, typeName;
      public final Class<?> valueClass; public final int[] dimensions; public final boolean enumeration;
      public Field(long id,String name,String modifier,String typeName,Class<?> valueClass,int[] dimensions,boolean enumeration) {
         this.id=id; this.name=name; this.modifier=modifier; this.typeName=typeName;
         this.valueClass=valueClass; this.dimensions=dimensions; this.enumeration=enumeration;
      }
   }
   public static final class CodecException extends RuntimeException {
      public CodecException(String m) { super(m); } public CodecException(String m,Throwable t) { super(m,t); }
   }
   public static final class Complex32 {
      public float real,imag; public Complex32() {} public Complex32(float r,float i){real=r;imag=i;}
      public boolean equals(Object o){if(!(o instanceof Complex32))return false;Complex32 c=(Complex32)o;return Float.floatToIntBits(real)==Float.floatToIntBits(c.real)&&Float.floatToIntBits(imag)==Float.floatToIntBits(c.imag);}
      public int hashCode(){return Float.floatToIntBits(real)*31+Float.floatToIntBits(imag);} public String toString(){return "("+real+","+imag+")";}
   }
   public static final class Complex64 {
      public double real,imag; public Complex64() {} public Complex64(double r,double i){real=r;imag=i;}
      public boolean equals(Object o){if(!(o instanceof Complex64))return false;Complex64 c=(Complex64)o;return Double.doubleToLongBits(real)==Double.doubleToLongBits(c.real)&&Double.doubleToLongBits(imag)==Double.doubleToLongBits(c.imag);}
      public int hashCode(){long a=Double.doubleToLongBits(real),b=Double.doubleToLongBits(imag);return (int)(a^(a>>>32))*31+(int)(b^(b>>>32));} public String toString(){return "("+real+","+imag+")";}
   }
   /** Packed c32 values in structure-of-arrays form for allocation-free access. */
   public static final class Complex32Array {
      public float[] re, im;
      public Complex32Array(){this(new float[0],new float[0]);}
      public Complex32Array(float[] re,float[] im){if(re==null||im==null||re.length!=im.length)throw new CodecException("complex component arrays must have equal lengths");this.re=re;this.im=im;}
      public int size(){return re.length;}
      public Complex32 get(int index){return new Complex32(re[index],im[index]);}
      public void append(Complex32Array other){if(other==null||other.size()==0)return;float[] nr=new float[size()+other.size()],ni=new float[size()+other.size()];System.arraycopy(re,0,nr,0,size());System.arraycopy(im,0,ni,0,size());System.arraycopy(other.re,0,nr,size(),other.size());System.arraycopy(other.im,0,ni,size(),other.size());re=nr;im=ni;}
   }
   /** Packed c64 values in structure-of-arrays form for allocation-free access. */
   public static final class Complex64Array {
      public double[] re, im;
      public Complex64Array(){this(new double[0],new double[0]);}
      public Complex64Array(double[] re,double[] im){if(re==null||im==null||re.length!=im.length)throw new CodecException("complex component arrays must have equal lengths");this.re=re;this.im=im;}
      public int size(){return re.length;}
      public Complex64 get(int index){return new Complex64(re[index],im[index]);}
      public void append(Complex64Array other){if(other==null||other.size()==0)return;double[] nr=new double[size()+other.size()],ni=new double[size()+other.size()];System.arraycopy(re,0,nr,0,size());System.arraycopy(im,0,ni,0,size());System.arraycopy(other.re,0,nr,size(),other.size());System.arraycopy(other.im,0,ni,size(),other.size());re=nr;im=ni;}
   }
   public static byte[] encode(Message m,byte[] descriptor,int hash,Field[] fields) {
      byte[] payload=encodePayload(m,fields); ByteArrayOutputStream out=new ByteArrayOutputStream(); writeU32(out,descriptor.length);out.write(descriptor,0,descriptor.length);writeU32(out,hash);out.write(payload,0,payload.length);return out.toByteArray();
   }
   public static Object decode(Class<?> type,byte[] descriptor,int hash,Field[] fields,byte[] wire) {
      if(wire==null||wire.length<8)throw malformed("truncated frame");long n=readU32(wire,0);
      if(n>MAX_DESCRIPTOR||n>wire.length-8)throw malformed("invalid descriptor length");
      if(n!=descriptor.length)throw new CodecException("schema descriptor mismatch");
      for(int i=0;i<(int)n;i++)if(wire[4+i]!=descriptor[i])throw new CodecException("schema descriptor mismatch");
      if(readU32(wire,4+(int)n)!=(hash&0xffffffffL))throw new CodecException("schema hash mismatch");
      byte[] body=new byte[wire.length-8-(int)n];System.arraycopy(wire,8+(int)n,body,0,body.length);return decodePayload(type,fields,body);
   }
   public static byte[] encodePayload(Message m,Field[] fields) {
      ByteArrayOutputStream out=new ByteArrayOutputStream();
      for(Field f:fields){Object v=get(m,f.name);
         if(f.dimensions.length>0){writeField(out,f.id,packFixed(f.valueClass,v,f.dimensions));continue;}
         if("optional".equals(f.modifier)){if(v!=null)writeField(out,f.id,packValue(f,v));}
         else if("repeated".equals(f.modifier)){for(Object x:(List<?>)v)writeField(out,f.id,packValue(f,x));}
         else if("packed".equals(f.modifier)){if("c32".equals(f.typeName)){Complex32Array xs=(Complex32Array)v;if(xs.re==null||xs.im==null||xs.re.length!=xs.im.length)throw new CodecException("complex component arrays must have equal lengths");if(xs.size()>0)writeField(out,f.id,packComplex(xs.re,xs.im));}else if("c64".equals(f.typeName)){Complex64Array xs=(Complex64Array)v;if(xs.re==null||xs.im==null||xs.re.length!=xs.im.length)throw new CodecException("complex component arrays must have equal lengths");if(xs.size()>0)writeField(out,f.id,packComplex(xs.re,xs.im));}else{List<?> xs=(List<?>)v;if(!xs.isEmpty()){ByteArrayOutputStream packed=new ByteArrayOutputStream();for(Object x:xs){byte[] b=packFixed(f.valueClass,x,new int[0]);packed.write(b,0,b.length);}writeField(out,f.id,packed.toByteArray());}}}
         else writeField(out,f.id,packValue(f,v));
      }return out.toByteArray();
   }
   @SuppressWarnings("unchecked")
   public static Object decodePayload(Class<?> type,Field[] fields,byte[] bytes){
      if(bytes==null)throw malformed("null payload");Object result=instance(type);int pos=0;
      while(pos<bytes.length){if(bytes.length-pos<8)throw malformed("truncated field header");long id=readU32(bytes,pos),len=readU32(bytes,pos+4);pos+=8;if(len>bytes.length-pos)throw malformed("truncated field payload");int end=pos+(int)len;Field f=find(fields,id);
         if(f!=null){byte[] part=new byte[(int)len];System.arraycopy(bytes,pos,part,0,part.length);Object decoded;
            if(f.dimensions.length>0)decoded=unpackFixed(f.valueClass,part,f.dimensions);
            else if("packed".equals(f.modifier)){if("c32".equals(f.typeName)){Complex32Array xs=unpackComplex32(part,0,part.length),old=(Complex32Array)get(result,f.name);if(old.size()==0)set(result,f.name,xs);else old.append(xs);}else if("c64".equals(f.typeName)){Complex64Array xs=unpackComplex64(part,0,part.length),old=(Complex64Array)get(result,f.name);if(old.size()==0)set(result,f.name,xs);else old.append(xs);}else{int size=fixedSize(f.valueClass);if(size<0||part.length%size!=0)throw malformed("invalid packed field length");List<Object> xs=(List<Object>)get(result,f.name);for(int p=0;p<part.length;p+=size){byte[] one=new byte[size];System.arraycopy(part,p,one,0,size);xs.add(unpackFixed(f.valueClass,one,new int[0]));}}pos=end;continue;}
            else decoded=unpackValue(f,part);
            if("repeated".equals(f.modifier))((List<Object>)get(result,f.name)).add(decoded);else set(result,f.name,decoded);
         }pos=end;
      }return result;
   }
   private static Field find(Field[] fs,long id){for(Field f:fs)if(f.id==id)return f;return null;}
   private static byte[] packFixed(Class<?> type,Object value,int[] dims){
      if(dims.length>0){if(value==null||!value.getClass().isArray()||Array.getLength(value)!=dims[0])throw new CodecException("fixed array has wrong length");int[] rest=tail(dims);ByteArrayOutputStream out=new ByteArrayOutputStream();for(int i=0;i<Array.getLength(value);i++){byte[] b=packFixed(type,Array.get(value,i),rest);out.write(b,0,b.length);}return out.toByteArray();}
      if(Message.class.isAssignableFrom(type)){ByteArrayOutputStream out=new ByteArrayOutputStream();for(Field f:messageFields(type)){if(!"required".equals(f.modifier))throw new CodecException("fixed struct has non-required field");byte[] b=packFixed(f.valueClass,get(value,f.name),f.dimensions);out.write(b,0,b.length);}return out.toByteArray();}
      return packValue(new Field(0,"","","",type,new int[0],EnumValue.class.isAssignableFrom(type)),value);
   }
   private static Object unpackFixed(Class<?> type,byte[] bytes,int[] dims){
      if(dims.length>0){int[] rest=tail(dims);int size=fixedSize(type,rest);if(size<0||bytes.length!=size*dims[0])throw malformed("invalid fixed array length");Class<?> component=rest.length==0?type:Array.newInstance(type,rest).getClass();Object array=Array.newInstance(component,dims[0]);for(int i=0;i<dims[0];i++){byte[] b=new byte[size];System.arraycopy(bytes,i*size,b,0,size);Array.set(array,i,unpackFixed(type,b,rest));}return array;}
      if(Message.class.isAssignableFrom(type)){int size=fixedSize(type);if(size!=bytes.length)throw malformed("invalid fixed struct length");Object v=instance(type);int pos=0;for(Field f:messageFields(type)){int n=fixedSize(f.valueClass,f.dimensions);byte[] b=new byte[n];System.arraycopy(bytes,pos,b,0,n);set(v,f.name,unpackFixed(f.valueClass,b,f.dimensions));pos+=n;}return v;}
      return unpackValue(new Field(0,"","","",type,new int[0],EnumValue.class.isAssignableFrom(type)),bytes);
   }
   private static int[] tail(int[] a){int[] b=new int[a.length-1];System.arraycopy(a,1,b,0,b.length);return b;}
   private static int fixedSize(Class<?> type){return fixedSize(type,new int[0]);}
   private static int fixedSize(Class<?> t,int[] dims){int n;
      if(t==Boolean.class||t==Byte.class)n=1;else if(t==Short.class)n=2;else if(t==Integer.class||t==Float.class||EnumValue.class.isAssignableFrom(t))n=4;else if(t==Long.class||t==Double.class||t==Complex32.class)n=8;else if(t==Complex64.class)n=16;
      else if(Message.class.isAssignableFrom(t)){n=0;for(Field f:messageFields(t)){if(!"required".equals(f.modifier))return -1;int x=fixedSize(f.valueClass,f.dimensions);if(x<0||n>Integer.MAX_VALUE-x)return -1;n+=x;}}else return -1;
      for(int d:dims){if(n>Integer.MAX_VALUE/d)return -1;n*=d;}return n;
   }
   private static byte[] packValue(Field f,Object v){String t=f.typeName.length()==0?typeName(f.valueClass):f.typeName;
      if("string".equals(t)){if(v==null)throw new CodecException("null string");return ((String)v).getBytes(StandardCharsets.UTF_8);}
      if(f.enumeration){if(!(v instanceof EnumValue))throw new CodecException("invalid enum value");return integer(((EnumValue)v).wireValue(),4);}
      if("bool".equals(t)){if(!(v instanceof Boolean))throw new CodecException("invalid bool");return new byte[]{(byte)(((Boolean)v)?1:0)};}
      if("int8".equals(t))return integer(((Number)v).byteValue(),1);if("int16".equals(t))return integer(((Number)v).shortValue(),2);if("int32".equals(t))return integer(((Number)v).intValue(),4);if("int64".equals(t))return integer(((Number)v).longValue(),8);
      if("fl32".equals(t))return integer(Float.floatToIntBits(((Number)v).floatValue()),4);if("fl64".equals(t))return integer(Double.doubleToLongBits(((Number)v).doubleValue()),8);
      if("c32".equals(t)){Complex32 c=(Complex32)v;return join(integer(Float.floatToIntBits(c.real),4),integer(Float.floatToIntBits(c.imag),4));}if("c64".equals(t)){Complex64 c=(Complex64)v;return join(integer(Double.doubleToLongBits(c.real),8),integer(Double.doubleToLongBits(c.imag),8));}
      if(v instanceof Message)return encodePayload((Message)v,messageFields(v.getClass()));throw new CodecException("unsupported SDL type: "+t);
   }
   private static byte[] packComplex(float[] re,float[] im){if(re==null||im==null||re.length!=im.length)throw new CodecException("complex component arrays must have equal lengths");if(re.length>Integer.MAX_VALUE/8)throw new CodecException("packed complex field is too large");byte[] out=new byte[re.length*8];for(int i=0;i<re.length;i++){putInteger(out,i*8,Float.floatToIntBits(re[i]),4);putInteger(out,i*8+4,Float.floatToIntBits(im[i]),4);}return out;}
   private static byte[] packComplex(double[] re,double[] im){if(re==null||im==null||re.length!=im.length)throw new CodecException("complex component arrays must have equal lengths");if(re.length>Integer.MAX_VALUE/16)throw new CodecException("packed complex field is too large");byte[] out=new byte[re.length*16];for(int i=0;i<re.length;i++){putInteger(out,i*16,Double.doubleToLongBits(re[i]),8);putInteger(out,i*16+8,Double.doubleToLongBits(im[i]),8);}return out;}
   private static Complex32Array unpackComplex32(byte[] bytes,int offset,int length){if(length%8!=0)throw malformed("invalid packed field length");int count=length/8;float[] re=new float[count],im=new float[count];for(int i=0;i<count;i++){re[i]=Float.intBitsToFloat((int)readInteger(bytes,offset+i*8,4));im[i]=Float.intBitsToFloat((int)readInteger(bytes,offset+i*8+4,4));}return new Complex32Array(re,im);}
   private static Complex64Array unpackComplex64(byte[] bytes,int offset,int length){if(length%16!=0)throw malformed("invalid packed field length");int count=length/16;double[] re=new double[count],im=new double[count];for(int i=0;i<count;i++){re[i]=Double.longBitsToDouble(readInteger(bytes,offset+i*16,8));im[i]=Double.longBitsToDouble(readInteger(bytes,offset+i*16+8,8));}return new Complex64Array(re,im);}
   private static Object unpackValue(Field f,byte[] b){String t=f.typeName.length()==0?typeName(f.valueClass):f.typeName;
      if("string".equals(t)){try{CharsetDecoder d=StandardCharsets.UTF_8.newDecoder().onMalformedInput(CodingErrorAction.REPORT).onUnmappableCharacter(CodingErrorAction.REPORT);return d.decode(ByteBuffer.wrap(b)).toString();}catch(CharacterCodingException e){throw new CodecException("invalid UTF-8",e);}}
      if(Message.class.isAssignableFrom(f.valueClass))return decodePayload(f.valueClass,messageFields(f.valueClass),b);
      int size=wireSize(t);if(b.length!=size)throw malformed("invalid scalar size for "+t);
      if(f.enumeration){int x=(int)readInteger(b,0);try{return f.valueClass.getMethod("fromWire",Integer.TYPE).invoke(null,Integer.valueOf(x));}catch(Exception e){throw new CodecException("invalid enum value",e);}}
      if("bool".equals(t)){if(b[0]!=0&&b[0]!=1)throw malformed("invalid bool");return Boolean.valueOf(b[0]!=0);}
      if("int8".equals(t))return Byte.valueOf((byte)readInteger(b,0));if("int16".equals(t))return Short.valueOf((short)readInteger(b,0));if("int32".equals(t))return Integer.valueOf((int)readInteger(b,0));if("int64".equals(t))return Long.valueOf(readInteger(b,0));
      if("fl32".equals(t))return Float.valueOf(Float.intBitsToFloat((int)readInteger(b,0)));if("fl64".equals(t))return Double.valueOf(Double.longBitsToDouble(readInteger(b,0)));
      if("c32".equals(t))return new Complex32(Float.intBitsToFloat((int)readInteger(b,0,4)),Float.intBitsToFloat((int)readInteger(b,4,4)));if("c64".equals(t))return new Complex64(Double.longBitsToDouble(readInteger(b,0,8)),Double.longBitsToDouble(readInteger(b,8,8)));
      throw malformed("unsupported SDL type");
   }
   private static int wireSize(String t){if("bool".equals(t)||"int8".equals(t))return 1;if("int16".equals(t))return 2;if("int32".equals(t)||"fl32".equals(t))return 4;if("int64".equals(t)||"fl64".equals(t)||"c32".equals(t))return 8;if("c64".equals(t))return 16;return 4;}
   private static String typeName(Class<?> c){if(c==Boolean.class)return "bool";if(c==Byte.class)return "int8";if(c==Short.class)return "int16";if(c==Integer.class)return "int32";if(c==Long.class)return "int64";if(c==Float.class)return "fl32";if(c==Double.class)return "fl64";if(c==Complex32.class)return "c32";if(c==Complex64.class)return "c64";if(c==String.class)return "string";return "message";}
   private static byte[] integer(long v,int n){byte[] b=new byte[n];for(int i=0;i<n;i++){int s=(LITTLE?i:n-1-i)*8;b[i]=(byte)(v>>>s);}return b;}
   private static void putInteger(byte[] b,int p,long v,int n){for(int i=0;i<n;i++){int s=(LITTLE?i:n-1-i)*8;b[p+i]=(byte)(v>>>s);}}
   private static long readInteger(byte[] b,int p){return readInteger(b,p,b.length);}
   private static long readInteger(byte[] b,int p,int n){long v=0;if(LITTLE){for(int i=n-1;i>=0;i--)v=(v<<8)|(b[p+i]&255L);}else{for(int i=0;i<n;i++)v=(v<<8)|(b[p+i]&255L);}return v;}
   private static long readU32(byte[] b,int p){return readInteger(new byte[]{b[p],b[p+1],b[p+2],b[p+3]},0)&0xffffffffL;}
   private static void writeU32(ByteArrayOutputStream o,long n){byte[] b=integer(n,4);o.write(b,0,b.length);}
   private static void writeField(ByteArrayOutputStream o,long id,byte[] b){writeU32(o,id);writeU32(o,b.length);o.write(b,0,b.length);}
   private static byte[] join(byte[] a,byte[] b){byte[] x=new byte[a.length+b.length];System.arraycopy(a,0,x,0,a.length);System.arraycopy(b,0,x,a.length,b.length);return x;}
   private static Field[] messageFields(Class<?> t){try{return (Field[])t.getField("SDL_FIELDS").get(null);}catch(Exception e){throw new CodecException("missing SDL fields",e);}}
   private static Object instance(Class<?> t){try{return t.getDeclaredConstructor().newInstance();}catch(Exception e){throw new CodecException("cannot instantiate message",e);}}
   private static Object get(Object o,String n){try{return o.getClass().getField(n).get(o);}catch(Exception e){throw new CodecException("cannot read "+n,e);}}
   private static void set(Object o,String n,Object v){try{o.getClass().getField(n).set(o,v);}catch(Exception e){throw new CodecException("cannot set "+n,e);}}
   private static CodecException malformed(String m){return new CodecException(m);}
   public static String display(Message m,Field[] fs){StringBuilder s=new StringBuilder(m.getClass().getSimpleName()).append('{');for(int i=0;i<fs.length;i++){if(i>0)s.append(", ");s.append(fs[i].name).append('=').append(get(m,fs[i].name));}return s.append('}').toString();}
}
