% Generated by the SDL Matlab backend.
function varargout=sdl_matlab_runtime(action,varargin)
switch action
case 'description'
 types=varargin{1};if ischar(types),types={types};end
 messages=containers.Map();enums=containers.Map();
 for k=1:numel(types),s=parse_catalogue(feval(types{k},'description'));[messages,enums]=merge_schema(messages,enums,s);end
 varargout{1}=render_schema(messages,enums);
case 'prepare'
 s=parse_catalogue(varargin{1});types={};if numel(varargin)>1,types=varargin{2};end;if ischar(types),types={types};end
 localmessages=containers.Map();localenums=containers.Map();
 for k=1:numel(types),local=parse_catalogue(feval(types{k},'description'));[localmessages,localenums]=merge_schema(localmessages,localenums,local);end
 s.local=containers.Map();s.bindings=containers.Map();s.sizes=containers.Map();s.exact=containers.Map();s.exact_cache=containers.Map();
 names=keys(localmessages);
 for k=1:numel(names),fn=identifier(names{k});if exist(fn,'file'),s.local(names{k})=feval(fn,'fields');end,end
 for k=1:numel(s.names)
  name=s.names{k};s.sizes(name)=fixed_size(s,name,{},0);remote=s.messages(name);local={};if isKey(s.local,name),local=s.local(name);end
  binding=zeros(numel(remote),1);exact=numel(local)==numel(remote);
  for j=1:numel(remote)
   f=remote{j};for z=1:numel(local),l=local{z};if l.id~=f.id,continue;end
    if ~strcmp(l.type,f.type)||~isequal(l.dims(:),f.dims(:))||~strcmp(cardinality(l.modifier),cardinality(f.modifier)),error('SDL:SchemaMismatch','incompatible field');end
    binding(j)=z;break
   end
   exact=exact&&binding(j)>0;
  end
  s.bindings(name)=binding;s.exact(name)=exact;
 end
 for k=1:numel(s.names),exact_type(s,s.names{k},{});end
 varargout{1}=s;
case 'encode'
 ctx=varargin{1};name=varargin{2};value=varargin{3};id=find(strcmp(ctx.names,name),1);if isempty(id),error('SDL:SchemaMismatch','unknown type');end
 body=write_message(ctx,name,value);varargout{1}=[count_bytes(id);body(:)];
case 'decode'
 ctx=varargin{1};data=uint8(varargin{2}(:));[id,pos]=read_count(data,1);if id<1||id>numel(ctx.names),error('SDL:Malformed','unknown message ID');end
 name=ctx.names{id};[value,pos]=read_message(ctx,name,data,pos,0,false);
 if pos~=numel(data)+1,error('SDL:Malformed','trailing bytes');end
 varargout{1}=value;if nargout>1,varargout{2}=name;end
case 'display'
 varargout{1}=evalc('disp(varargin{1})');
otherwise,error('SDL:InvalidAction','unknown action');
end
end
function result=identifier(name),result=regexprep(name,'\W','_');if strncmp(result,'__',2),result=['sdl' result];end,end
function m=cardinality(m),if any(strcmp(m,{'packed','repeated'})),m='sequence';end,end
function s=parse_catalogue(text)
if isa(text,'uint8'),valid_utf8(text);text=native2unicode(text(:)','UTF-8');end
if ~ischar(text)||numel(unicode2native(text,'UTF-8'))>1048576||numel(text)<5||~strcmp(text(1:5),sprintf('SDL2\n'))||text(end)~=char(10)||any(text==0),error('SDL:Descriptor','expected SDL2 catalogue');end
lines=strsplit(text,char(10),'CollapseDelimiters',false);s.messages=containers.Map();s.enums=containers.Map();s.fixed_cache=containers.Map();s.heights=containers.Map();i=2;previousm='';previouse='';
while i<numel(lines)
 h=regexp(lines{i},'^(message|enum) ([\w$]+) \{$','tokens','once');if isempty(h),error('SDL:Descriptor','invalid declaration');end
 kind=h{1};name=h{2};i=i+1;if numel(unicode2native(name,'UTF-8'))>65535,error('SDL:Descriptor','identifier limit');end
 if strcmp(kind,'message')
  ordered={previousm,name};if strcmp(previousm,name)||(~isempty(previousm)&&~isequal(sort(ordered),ordered)),error('SDL:Descriptor','message order');end;previousm=name;fields={};ids=[];names={};if s.messages.Count>=65535,error('SDL:Descriptor','message limit');end
  while i<numel(lines)&&~strcmp(lines{i},'}')
   f=regexp(lines{i},'^  ([0-9]+): (required|optional|repeated|packed) ([\w$]+)((?:\[[0-9]+\])*) ([\w$]+);$','tokens','once');if isempty(f),error('SDL:Descriptor','invalid field');end
   if numel(unicode2native(f{3},'UTF-8'))>65535||numel(unicode2native(f{5},'UTF-8'))>65535,error('SDL:Descriptor','identifier limit');end
   id=decimal(f{1});dims=regexp(f{4},'\[([0-9]+)\]','tokens');dimensions=zeros(1,numel(dims));for z=1:numel(dims),dimensions(z)=decimal(dims{z}{1});end
   if id==0||(~isempty(ids)&&id<=ids(end))||any(strcmp(names,f{5}))||numel(dimensions)>255||any(dimensions==0)||(~isempty(dimensions)&&~strcmp(f{2},'required'))||numel(fields)>=65535,error('SDL:Descriptor','invalid field metadata');end
   fields{end+1}=struct('id',uint32(id),'name',f{5},'modifier',f{2},'type',f{3},'dims',dimensions);ids(end+1)=id;names{end+1}=f{5};i=i+1;
  end
  s.messages(name)=fields;
 else
  ordered={previouse,name};if strcmp(previouse,name)||(~isempty(previouse)&&~isequal(sort(ordered),ordered)),error('SDL:Descriptor','enum order');end;previouse=name;items={};values=int32([]);names={};if s.enums.Count>=65535,error('SDL:Descriptor','enum limit');end
  while i<numel(lines)&&~strcmp(lines{i},'}')
   f=regexp(lines{i},'^  ([\w$]+) = (-?[0-9]+);$','tokens','once');if isempty(f),error('SDL:Descriptor','invalid enum');end
   if numel(items)>=65535||numel(unicode2native(f{1},'UTF-8'))>65535,error('SDL:Descriptor','enum limit');end
   n=str2double(f{2});if ~isfinite(n)||n<-2147483648||n>2147483647||any(values==int32(n))||any(strcmp(names,f{1})),error('SDL:Descriptor','invalid enum value');end
   items{end+1}=f{1};values(end+1)=int32(n);names{end+1}=f{1};i=i+1;
  end
  if isempty(items),error('SDL:Descriptor','empty enum');end;s.enums(name)=struct('names',{items},'values',values);
 end
 if i>=numel(lines)||~strcmp(lines{i},'}'),error('SDL:Descriptor','unclosed declaration');end;i=i+1;
end
s.names=sort(keys(s.messages));if isempty(s.names),error('SDL:Descriptor','empty catalogue');end
for k=1:numel(s.names)
 name=s.names{k};if primitive_size(name)>0||strcmp(name,'string')||isKey(s.enums,name),error('SDL:Descriptor','ambiguous type');end
 fields=s.messages(name);
 for j=1:numel(fields)
  f=fields{j};if primitive_size(f.type)==0&&~strcmp(f.type,'string')&&~isKey(s.messages,f.type)&&~isKey(s.enums,f.type),error('SDL:Descriptor','unknown type');end
  if ~isempty(f.dims)||strcmp(f.modifier,'packed'),n=fixed_size(s,f.type,{},0);if n<=0||n*prod(f.dims)>4294967295,error('SDL:Descriptor','variable or oversized fixed element');end,end
 end
 visit(s,name,{},0);
end
names=keys(s.enums);for k=1:numel(names),if primitive_size(names{k})>0||strcmp(names{k},'string'),error('SDL:Descriptor','reserved enum name');end,end
end
function n=decimal(text),n=str2double(text);if ~isfinite(n)||n<0||n>4294967295||n~=fix(n),error('SDL:Descriptor','uint32 overflow');end,end
function height=visit(s,name,active,depth)
if depth>64,error('SDL:Descriptor','deep schema');end
if isKey(s.heights,name),height=s.heights(name);if depth+height>64,error('SDL:Descriptor','deep schema');end;return;end
if any(strcmp(active,name)),error('SDL:Descriptor','recursive schema');end;active{end+1}=name;height=0;
f=s.messages(name);for k=1:numel(f),if isKey(s.messages,f{k}.type),height=max(height,1+visit(s,f{k}.type,active,depth+1));end,end
if depth+height>64,error('SDL:Descriptor','deep schema');end;s.heights(name)=height;
end
function n=fixed_size(s,name,active,depth)
if depth>64,n=-1;return;end
if isKey(s.fixed_cache,name),n=s.fixed_cache(name);return;end
n=compute_fixed_size(s,name,active,depth);s.fixed_cache(name)=n;
end
function n=compute_fixed_size(s,name,active,depth)
n=primitive_size(name);if n>0,return;end;if isKey(s.enums,name),n=4;return;end
if ~isKey(s.messages,name)||depth>64||any(strcmp(active,name)),n=-1;return;end
fields=s.messages(name);if isempty(fields),n=-1;return;end;active{end+1}=name;n=0;
for k=1:numel(fields),f=fields{k};if ~strcmp(f.modifier,'required'),n=-1;return;end
 size=fixed_size(s,f.type,active,depth+1);if size<0,n=-1;return;end;n=n+size*prod(f.dims);if n>4294967295,error('SDL:Descriptor','fixed size overflow');end
end
end
function [messages,enums]=merge_schema(messages,enums,s)
names=keys(s.messages);for k=1:numel(names),n=names{k};if isKey(messages,n)&&~isequal(messages(n),s.messages(n)),error('SDL:Descriptor','conflicting message');end;messages(n)=s.messages(n);end
names=keys(s.enums);for k=1:numel(names),n=names{k};if isKey(enums,n)&&~isequal(enums(n),s.enums(n)),error('SDL:Descriptor','conflicting enum');end;enums(n)=s.enums(n);end
end
function text=render_schema(messages,enums)
text=sprintf('SDL2\n');names=sort(keys(messages));for k=1:numel(names),name=names{k};text=[text sprintf('message %s {\n',name)];fields=messages(name);
 for j=1:numel(fields),f=fields{j};dims='';for n=f.dims,dims=[dims sprintf('[%.0f]',n)];end;text=[text sprintf('  %.0f: %s %s%s %s;\n',f.id,f.modifier,f.type,dims,f.name)];end;text=[text sprintf('}\n')];
end
names=sort(keys(enums));for k=1:numel(names),name=names{k};e=enums(name);text=[text sprintf('enum %s {\n',name)];for j=1:numel(e.names),text=[text sprintf('  %s = %.0f;\n',e.names{j},e.values(j))];end;text=[text sprintf('}\n')];end
parse_catalogue(text);
end
function b=count_bytes(n)
if n<0||n>4294967295||n~=fix(n),error('SDL:Malformed','counter overflow');end
b=zeros(5,1,'uint8');i=1;while n>=128,b(i)=uint8(mod(n,128)+128);n=floor(n/128);i=i+1;end;b(i)=uint8(n);b=b(1:i);
end
function [n,pos]=read_count(b,pos)
n=0;for k=0:4
 if pos>numel(b),error('SDL:Malformed','truncated counter');end;x=double(b(pos));pos=pos+1;if k==4&&x>15,error('SDL:Malformed','counter overflow');end;n=n+mod(x,128)*2^(7*k);
 if x<128,if k>0&&x==0,error('SDL:Malformed','noncanonical counter');end;return;end
end
error('SDL:Malformed','invalid counter');
end
function b=write_message(ctx,name,value)
if ~isKey(ctx.local,name)||~ctx.exact(name),error('SDL:SchemaMismatch','encoding requires emission catalogue');end
fields=ctx.messages(name);local=ctx.local(name);binding=ctx.bindings(name);parts=cell(numel(fields)*2,1);p=0;
for k=1:numel(fields)
 f=fields{k};l=local{binding(k)};x=value.(l.name);
 if strcmp(f.modifier,'optional'),present=~isempty(x)||(strcmp(f.type,'string')&&ischar(x));p=p+1;parts{p}=count_bytes(present);if ~present,continue;end
 elseif any(strcmp(f.modifier,{'packed','repeated'}))
  if strcmp(l.modifier,'packed'),if isempty(l.terminal),n=numel(x);else,n=packed_length(x,l.terminal);end
  else,n=numel(x);end
  p=p+1;parts{p}=count_bytes(n);
  if strcmp(l.modifier,'packed'),validate_packed_enums(ctx,l,x);payload=pack_packed_field(l,x);
  else,items=cell(n,1);for j=1:n,items{j}=write_value(ctx,f.type,x{j},f.dims);end;payload=vertcat(items{:});end
  p=p+1;parts{p}=payload;continue
 end
 p=p+1;parts{p}=write_value(ctx,f.type,x,f.dims);
end
if p==0,b=uint8([]);else,b=vertcat(parts{1:p});end
end
function validate_packed_enums(ctx,f,x)
if isempty(f.terminal),if isKey(ctx.enums,f.type),e=ctx.enums(f.type);if any(~ismember(x,e.values)),error('SDL:InvalidEnum','invalid enum');end,end
else,for z=1:numel(f.terminal),term=f.terminal{z};if term.enum,e=ctx.enums(term.type);v=packed_get_path(x,term.path);if any(~ismember(v(:),e.values)),error('SDL:InvalidEnum','invalid enum');end,end,end
end
end
function b=write_value(ctx,type,x,dims)
if ~isempty(dims)
 if numel(x)~=prod(dims),error('SDL:InvalidValue','fixed array dimensions');end;parts=cell(numel(x),1);for k=1:numel(x),parts{k}=write_value(ctx,type,x(k),[]);end;b=vertcat(parts{:});return
end
if isKey(ctx.messages,type),b=write_message(ctx,type,x);return;end
if strcmp(type,'string'),bytes=unicode2native(char(x),'UTF-8');valid_utf8(bytes);b=[count_bytes(numel(bytes));uint8(bytes(:))];return;end
if isKey(ctx.enums,type),e=ctx.enums(type);if ~isscalar(x)||~ismember(x,e.values),error('SDL:InvalidEnum','invalid enum');end;type='int32';end
if ~isscalar(x),error('SDL:InvalidValue','scalar required');end;b=pack_packed(type,x,false);
end
function b=pack_packed_field(f,x)
if isfield(f,'terminal')&&~isempty(f.terminal)
 n=packed_length(x,f.terminal);record_size=0;parts=cell(numel(f.terminal),1);field_sizes=zeros(numel(f.terminal),1);
 for z=1:numel(f.terminal)
  term=f.terminal{z}; vals=packed_get_path(x,term.path);
  parts{z}=pack_packed(term.type,vals,term.enum);field_sizes(z)=type_size(term.type)*max(1,prod(term.dims));record_size=record_size+field_sizes(z);
 end
 if n==0,b=uint8([]);return;end
 matrix=zeros(record_size,n,'uint8');offset=1;
 for z=1:numel(f.terminal)
  sz=field_sizes(z);matrix(offset:offset+sz-1,:)=reshape(parts{z},sz,n);offset=offset+sz;
 end
 b=matrix(:);
else
 b=pack_packed(f.type,x,f.enum);
end
end
function n=packed_length(x,paths)
n=[];for z=1:numel(paths),term=paths{z};v=packed_get_path(x,term.path);records=numel(v)/max(1,prod(term.dims));if records~=fix(records),error('SDL:InvalidValue','SoA terminal array has invalid size');end;if isempty(n),n=records;elseif n~=records,error('SDL:InvalidValue','packed struct array columns have unequal lengths');end,end
if isempty(n),n=0;end
end
function v=packed_get_path(x,path)
parts=strsplit(path,'.');v=x;for z=1:numel(parts),v=v.(parts{z});end
end
function b=pack_packed(t,values,is_enum)
if isempty(values),b=uint8([]);return;end
if is_enum
 if iscell(values),nums=cell2mat(values(:)');else,nums=values(:);end;b=typecast(int32(nums),'uint8');unit=4;
elseif any(strcmp(t,{'c32','c64'}))
 if iscell(values),nums=cellfun(@real,values);imags=cellfun(@imag,values);else,nums=real(values);imags=imag(values);end
 if strcmp(t,'c32'),nums=single(nums);imags=single(imags);else,nums=double(nums);imags=double(imags);end
 raw=[nums(:)';imags(:)'];b=typecast(raw(:),'uint8'); unit=type_size(t)/2;
else
 if iscell(values),nums=cell2mat(values(:)');else,nums=values(:);end
 if strcmp(t,'bool'),if any(nums(:)~=0 & nums(:)~=1),error('SDL:InvalidValue','invalid bool');end;b=uint8(logical(nums));elseif strcmp(t,'fl32'),b=typecast(single(nums),'uint8');elseif strcmp(t,'fl64'),b=typecast(double(nums),'uint8');else,b=typecast(cast(nums,t),'uint8');end;unit=type_size(t);
end
if host_little()&&unit>1,b=reshape(b,unit,[]);b=flipud(b);b=b(:);end
b=uint8(b(:));
end
function b=pack_raw(t,x)
switch t
case 'bool',b=uint8(logical(x));
case {'int8','int16','int32','int64'},b=typecast(cast(x,t),'uint8');
case {'fl32','fl64'},if strcmp(t,'fl32'),x=single(x);else,x=double(x);end;b=typecast(x,'uint8');
case {'c32','c64'},if strcmp(t,'c32'),z=single([real(x),imag(x)]);else,z=double([real(x),imag(x)]);end;b=typecast(z,'uint8');
end
if host_little()
 if any(strcmp(t,{'c32','c64'})),unit=type_size(t)/2;else,unit=type_size(t);end
 if unit>1,b=reshape(b,unit,[]);b=flipud(b);b=b(:);end
end
b=uint8(b(:));
end
function x=unpack_value(t,b,is_enum)
sz=type_size(t);if (~isempty(sz)&&numel(b)~=sz),error('SDL:Malformed',['invalid scalar size for ' t]);end
if host_little()
 if any(strcmp(t,{'c32','c64'})),unit=sz/2;else,unit=sz;end
 if unit>1,b=reshape(b,unit,[]);b=flipud(b);b=b(:);end
end
switch t
case 'bool',if b(1)>1,error('SDL:Malformed','invalid bool');end;x=logical(b(1));
case {'int8','int16','int32','int64'},x=typecast(uint8(b),t);
case {'fl32','fl64'},if strcmp(t,'fl32'),x=typecast(uint8(b),'single');else,x=typecast(uint8(b),'double');end
case {'c32','c64'},if strcmp(t,'c32'),z=typecast(uint8(b),'single');else,z=typecast(uint8(b),'double');end;x=complex(z(1),z(2));
case 'string',if isempty(b),x='';else,x=native2unicode(uint8(b(:))','UTF-8');end
otherwise,x=typecast(uint8(b),'int32');
end
end
function out=unpack_packed_field(f,b)
if ~isempty(f.terminal)
 recsize=0;sizes=zeros(numel(f.terminal),1);for z=1:numel(f.terminal),term=f.terminal{z};sizes(z)=type_size(term.type)*max(1,prod(term.dims));recsize=recsize+sizes(z);end
 if recsize==0||mod(numel(b),recsize),error('SDL:Malformed','invalid packed struct payload length');end
 n=numel(b)/recsize;records=reshape(uint8(b(:)),recsize,n);out=struct();pos=1;
 for z=1:numel(f.terminal)
  term=f.terminal{z};sz=sizes(z);column_bytes=records(pos:pos+sz-1,:);
  shape=[fliplr(term.dims),n];if isempty(term.dims),shape=[n,1];end
  out=set_path(out,term.path,reshape(unpack_packed(term.type,column_bytes(:),term.enum),shape));pos=pos+sz;
 end
else
 sz=type_size(f.type);if isempty(sz)||mod(numel(b),sz),error('SDL:Malformed','invalid packed payload length');end
 count=numel(b)/sz;if any(strcmp(f.type,{'c32','c64'})),column_bytes=reshape(b,sz,count);else,column_bytes=reshape(b,sz,count);end;out=unpack_packed(f.type,column_bytes,f.enum);
end
end
function values=unpack_packed(t,columns,is_enum)
sz=type_size(t);if is_enum,t='int32';end
if host_little()
 if any(strcmp(t,{'c32','c64'})),unit=sz/2;else,unit=sz;end
 if unit>1,columns=reshape(columns,unit,[]);columns=flipud(columns);columns=columns(:);end
end
if strcmp(t,'bool')
 if any(columns(:)>1),error('SDL:Malformed','invalid packed bool value');end;values=logical(columns(:));
elseif any(strcmp(t,{'c32','c64'}))
 if strcmp(t,'c32'),raw=typecast(uint8(columns(:)),'single');else,raw=typecast(uint8(columns(:)),'double');end
 components=reshape(raw,2,[]);values=complex(components(1,:),components(2,:)).';
else
 if strcmp(t,'fl32'),values=typecast(uint8(columns(:)),'single');elseif strcmp(t,'fl64'),values=typecast(uint8(columns(:)),'double');else,values=typecast(uint8(columns(:)),t);end;values=values(:);
end
end
function s=set_path(s,path,value)
parts=strsplit(path,'.');if numel(parts)==1,s.(parts{1})=value;else,if ~isfield(s,parts{1}),s.(parts{1})=struct();end;s.(parts{1})=set_path(s.(parts{1}),strjoin(parts(2:end),'.'),value);end
end
function yes=exact_type(ctx,name,active)
if ~isKey(ctx.messages,name),yes=true;return;end
if isKey(ctx.exact_cache,name),yes=ctx.exact_cache(name);return;end
if ~ctx.exact(name)||any(strcmp(active,name)),yes=false;ctx.exact_cache(name)=false;return;end
active{end+1}=name;fields=ctx.messages(name);yes=true;for k=1:numel(fields),if ~exact_type(ctx,fields{k}.type,active),yes=false;break;end,end
ctx.exact_cache(name)=yes;
end
function [value,pos]=read_message(ctx,name,data,pos,depth,skip)
if depth>64,error('SDL:Malformed','nesting too deep');end
if ~skip&&~isKey(ctx.local,name),error('SDL:SchemaMismatch','unknown local message');end
fields=ctx.messages(name);binding=ctx.bindings(name);local={};value=[];if ~skip,local=ctx.local(name);value=feval(identifier(name),'new');end
for k=1:numel(fields)
 f=fields{k};n=1;if ~strcmp(f.modifier,'required'),[n,pos]=read_count(data,pos);end
 if strcmp(f.modifier,'optional')&&n>1,error('SDL:Malformed','optional count exceeds one');end
 size=fixed_size(ctx,f.type,{},0);if size>0,unit=size*prod(f.dims);if n>floor((numel(data)-pos+1)/unit),error('SDL:Malformed','truncated array');end
 elseif n>1048576,error('SDL:Malformed','variable sequence too large');end
 discard=skip||binding(k)==0;
 if any(strcmp(f.modifier,{'packed','repeated'}))
  l=[];if ~discard,l=local{binding(k)};end
  if ~discard&&strcmp(l.modifier,'packed')&&exact_type(ctx,f.type,{})
   bytes=size*n;if pos+bytes-1>numel(data),error('SDL:Malformed','truncated packed array');end
   x=unpack_packed_field(l,data(pos:pos+bytes-1));validate_packed_enums(ctx,l,x);pos=pos+bytes;value.(l.name)=x;
  else
   items=cell(n,1);for j=1:n,[items{j},pos]=read_value(ctx,f.type,f.dims,data,pos,depth+1,discard);end
   if ~discard
    if strcmp(l.modifier,'packed')
     if isempty(l.terminal),if n==0,x=unpack_packed_field(l,uint8([]));else,x=vertcat(items{:});end
     else,x=struct();for z=1:numel(l.terminal),term=l.terminal{z};values=cell(n,1);for j=1:n,values{j}=packed_get_path(items{j},term.path);end
       if n==0,vals=[];else,vals=cat(numel(term.dims)+1,values{:});end
       if isempty(term.dims),vals=vals(:);end;x=set_path(x,term.path,vals);
      end
     end
     value.(l.name)=x;
    else,value.(l.name)=items;end
   end
  end
 elseif n==1
  [x,pos]=read_value(ctx,f.type,f.dims,data,pos,depth+1,discard);if ~discard,l=local{binding(k)};value.(l.name)=x;end
 elseif ~discard,l=local{binding(k)};value.(l.name)=[];
 end
end
end
function [value,pos]=read_value(ctx,type,dims,data,pos,depth,skip)
if depth>64,error('SDL:Malformed','nesting too deep');end
if ~isempty(dims)
 n=prod(dims);items=cell(n,1);for k=1:n,[items{k},pos]=read_value(ctx,type,[],data,pos,depth+1,skip);end
 if skip,value=[];else,shape=fliplr(dims);if numel(shape)==1,shape=[shape 1];end;value=reshape([items{:}],shape);end;return
end
if isKey(ctx.messages,type),[value,pos]=read_message(ctx,type,data,pos,depth+1,skip);return;end
if strcmp(type,'string'),[n,pos]=read_count(data,pos);if n>numel(data)-pos+1,error('SDL:Malformed','truncated string');end
 b=data(pos:pos+n-1);valid_utf8(b);pos=pos+n;if skip,value=[];elseif isempty(b),value='';else,value=native2unicode(b(:)','UTF-8');end;return
end
is_enum=isKey(ctx.enums,type);if is_enum,n=4;else,n=primitive_size(type);end
if n==0||n>numel(data)-pos+1,error('SDL:Malformed','truncated scalar');end;b=data(pos:pos+n-1);pos=pos+n;
value=unpack_packed(type,b,is_enum);
if is_enum,e=ctx.enums(type);if ~ismember(value,e.values),error('SDL:InvalidEnum','invalid sender enum');end
 fn=identifier(type);if ~skip&&exist(fn,'file'),local=feval(fn);if ~ismember(value,cell2mat(struct2cell(local))),error('SDL:InvalidEnum','invalid local enum');end,end
end
if skip,value=[];end
end
function n=primitive_size(t)
switch t
case {'bool','int8'},n=1;case 'int16',n=2;case {'int32','fl32'},n=4;
case {'int64','fl64','c32'},n=8;case 'c64',n=16;otherwise,n=0;
end
end
function n=type_size(t),n=primitive_size(t);if n==0&&~strcmp(t,'string'),n=4;end,end
function yes=host_little(),[~,~,order]=computer;yes=strcmp(order,'L');end
function valid_utf8(b)
b=double(b(:));if all(b<128),return;end
p=1;while p<=numel(b)
 x=b(p);p=p+1;if x<128,continue;end
 if x>=194&&x<=223,n=1;v=mod(x,32);minimum=128;
 elseif x>=224&&x<=239,n=2;v=mod(x,16);minimum=2048;
 elseif x>=240&&x<=244,n=3;v=mod(x,8);minimum=65536;
 else,error('SDL:Malformed','invalid UTF-8');end
 if n>numel(b)-p+1,error('SDL:Malformed','truncated UTF-8');end
 for j=1:n,y=b(p);p=p+1;if y<128||y>191,error('SDL:Malformed','invalid UTF-8 continuation');end;v=v*64+mod(y,64);end
 if v<minimum||v>1114111||(v>=55296&&v<=57343),error('SDL:Malformed','invalid UTF-8 scalar');end
end
end
