% Generated by the SDL Matlab backend.
classdef sdl_mex_context < handle
 properties (SetAccess=private)
  Id
 end
 methods
  function obj=sdl_mex_context(id)
   obj.Id=id;
  end
  function delete(obj)
   if ~isempty(obj.Id)&&obj.Id~=0
    released=sdl_packed_mex('release',obj.Id); %#ok<NASGU>
    obj.Id=uint64(0);
   end
  end
 end
 methods (Static)
  function obj=prepare(description)
   if isa(description,'uint8'),bytes=description;else,bytes=uint8(unicode2native(description,'UTF-8'));end
   id=sdl_packed_mex('prepare',bytes);
   if id==0,obj=[];return;end
   try,obj=sdl_mex_context(id);
   catch err,released=sdl_packed_mex('release',id);rethrow(err);end %#ok<NASGU>
  end
 end
end
