function build_mex(output_dir)
% R2017a-compatible C Matrix API (separate complex real/imaginary planes).
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
if ~exist(output_dir,'dir'),mkdir(output_dir);end
generated_c=fullfile(fileparts(output_dir),'c');
mex(['-I' fullfile(root,'runtime','c')], ['-I' generated_c], ...
    'CFLAGS=$CFLAGS -std=c99 -flto', 'COPTIMFLAGS=-O3', ...
    'LDFLAGS=$LDFLAGS -flto', 'LDOPTIMFLAGS=-O3', ...
    '-outdir',output_dir,'-output','sdl_packed_mex', ...
    fullfile(root,'runtime','matlab','sdl_packed_mex.c'), ...
    fullfile(root,'runtime','c','sdl_wire.c'), ...
    fullfile(root,'runtime','c','sdl_dynamic.c'), ...
    fullfile(root,'runtime','c','type_engine.c'), ...
    fullfile(root,'runtime','c','type_registry.c'), ...
    fullfile(root,'runtime','c','type_codec.c'), ...
    fullfile(root,'runtime','c','type_display.c'), ...
    fullfile(generated_c,'benchmark.c'), ...
    fullfile(generated_c,'bench_cases.c'));
end
