with Ada.Finalization;
with Ada.Containers.Vectors;
with Ada.Strings.Unbounded;
with Interfaces;
with System;
package SDL_Runtime is
   Codec_Error : exception;
   subtype Int8 is Interfaces.Integer_8;
   subtype Int16 is Interfaces.Integer_16;
   subtype Int32 is Interfaces.Integer_32;
   subtype Int64 is Interfaces.Integer_64;
   subtype Float32 is Interfaces.IEEE_Float_32;
   subtype Float64 is Interfaces.IEEE_Float_64;
   subtype Text is Ada.Strings.Unbounded.Unbounded_String;
   type Complex32 is record
      Re, Im : Float32 := 0.0;
   end record;
   type Complex64 is record
      Re, Im : Float64 := 0.0;
   end record;
   type Bytes is array (Positive range <>) of Interfaces.Unsigned_8;
   package Byte_Vectors is new Ada.Containers.Vectors (Positive, Interfaces.Unsigned_8, Interfaces."=");
   subtype Buffer is Byte_Vectors.Vector;
   type Context is new Ada.Finalization.Controlled with private;
   overriding procedure Adjust (C : in out Context);
   overriding procedure Finalize (C : in out Context);
   function Prepare (Remote, Local : String; Use_Direct : Boolean := True) return Context;
   function Message_Id (C : Context; Name : String) return Interfaces.Unsigned_32;
   procedure Check_Encode (C : Context; Name : String);
   procedure Check_Wire (C : Context; Data : Bytes);
   function To_Bytes (B : Buffer) return Bytes;
   procedure Put_Count (B : in out Buffer; N : Interfaces.Unsigned_32);
   procedure Write (B : in out Buffer; V : Boolean);
   procedure Write (B : in out Buffer; V : Int8);
   procedure Write (B : in out Buffer; V : Int16);
   procedure Write (B : in out Buffer; V : Int32);
   procedure Write (B : in out Buffer; V : Int64);
   procedure Write (B : in out Buffer; V : Float32);
   procedure Write (B : in out Buffer; V : Float64);
   procedure Write (B : in out Buffer; V : Complex32);
   procedure Write (B : in out Buffer; V : Complex64);
   procedure Write (B : in out Buffer; V : Text);
   -- Direct codecs write into one exactly-sized output array. Read cursors
   -- are bounds checked; generated codecs validate counts, values and framing.
   function Direct_Layout (C : Context; Name : String) return Boolean;
   function Count_Size (N : Interfaces.Unsigned_32) return Positive;
   procedure Put_Count (Data : in out Bytes; Position : in out Natural; N : Interfaces.Unsigned_32);
   function Get_Count (Data : Bytes; Position : in out Natural) return Interfaces.Unsigned_32;
   procedure Put (Data : in out Bytes; Position : in out Natural; V : Boolean);
   procedure Get (Data : Bytes; Position : in out Natural; V : out Boolean);
   procedure Put (Data : in out Bytes; Position : in out Natural; V : Int8);
   procedure Get (Data : Bytes; Position : in out Natural; V : out Int8);
   procedure Put (Data : in out Bytes; Position : in out Natural; V : Int16);
   procedure Get (Data : Bytes; Position : in out Natural; V : out Int16);
   procedure Put (Data : in out Bytes; Position : in out Natural; V : Int32);
   procedure Get (Data : Bytes; Position : in out Natural; V : out Int32);
   procedure Put (Data : in out Bytes; Position : in out Natural; V : Int64);
   procedure Get (Data : Bytes; Position : in out Natural; V : out Int64);
   procedure Put (Data : in out Bytes; Position : in out Natural; V : Float32);
   procedure Get (Data : Bytes; Position : in out Natural; V : out Float32);
   procedure Put (Data : in out Bytes; Position : in out Natural; V : Float64);
   procedure Get (Data : Bytes; Position : in out Natural; V : out Float64);
   procedure Put (Data : in out Bytes; Position : in out Natural; V : Complex32);
   procedure Get (Data : Bytes; Position : in out Natural; V : out Complex32);
   procedure Put (Data : in out Bytes; Position : in out Natural; V : Complex64);
   procedure Get (Data : Bytes; Position : in out Natural; V : out Complex64);
   pragma Inline_Always (Put, Get);
   procedure Put (Data : in out Bytes; Position : in out Natural; V : Text);
   procedure Get (Data : Bytes; Position : in out Natural; V : out Text);
   subtype Value is System.Address;
   function Decode_Tree (C : Context; Data : Bytes) return Value;
   procedure Free_Tree (Tree : Value) with Import, Convention => C, External_Name => "sdl_ada_free";
   function Name_Of (Tree : Value) return String;
   function Field (C : Context; Tree : Value; Id : Interfaces.Unsigned_32) return Value;
   function Present (V : Value) return Boolean;
   function Length (V : Value) return Natural;
   function Item (V : Value; Index : Natural) return Value;
   function Message (V : Value) return Value;
   function Read (V : Value) return Boolean;
   function Read (V : Value) return Int8;
   function Read (V : Value) return Int16;
   function Read (V : Value) return Int32;
   function Read (V : Value) return Int64;
   function Read (V : Value) return Float32;
   function Read (V : Value) return Float64;
   function Read (V : Value) return Complex32;
   function Read (V : Value) return Complex64;
   function Read (V : Value) return Text;
private
   type Context is new Ada.Finalization.Controlled with record
      Handle : System.Address := System.Null_Address;
      Direct_Enabled : Boolean := True;
   end record;
end SDL_Runtime;
